name: Android CI

on:
  pull_request:
    types: [opened, edited, review_requested, closed]
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Cache Gradle dependencies
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
      
    - name: Set up JDK 21.0.3
      uses: actions/setup-java@v2
      with:
        java-version: '21.0.3+9.0.LTS'
        distribution: 'adopt'
      
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
      
    - name: Build with Gradle
      env:
          GOOGLE_SERVICES_KEY: ${{ secrets.GOOGLE_SERVICES_KEY }}
      run: ./gradlew build

    - name: Build apk debug project (APK)
      if: github.event.pull_request.merged == true
      run: ./gradlew assembleDebug
    
    - name: Get release file apk path
      if: github.event.pull_request.merged == true
      id: releaseApk
      run: echo "apkfile=$(find app/build/outputs/apk/debug/*.apk)" >> $GITHUB_OUTPUT

    - name: Upload Release Build to Artifacts
      if: github.event.pull_request.merged == true
      uses: actions/upload-artifact@v3
      with:
          name: release-artifacts
          path: ${{ steps.releaseApk.outputs.apkfile }}

    - name: Notify discord server
      if: github.event.pull_request.merged == true
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCROD_WEBHOOK_URL }}
        ARTIFACT_ID: ${{github.run_id}}
      run: chmod +x ./notify.sh && ./notify.sh 

    
    
  
    
    
